<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_SelectState</name>
   <tag></tag>
   <elementGuidId>b31b6a1d-2ed6-42a1-9e9c-644c0e152a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-11unzgr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Select State')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74cf8915-0c7b-40b4-860d-42e1ef2d059b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-11unzgr</value>
      <webElementGuid>c5a56d22-97cf-4b06-8f30-69860dc20c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NCRUttar PradeshHaryanaRajasthan</value>
      <webElementGuid>a52ed00c-2566-4e65-893a-bc8f46e1434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state&quot;)/div[@class=&quot;css-26l3qy-menu&quot;]/div[@class=&quot;css-11unzgr&quot;]</value>
      <webElementGuid>b6fa8942-1dbb-4cf9-9a65-28f2a2ec795f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state']/div[2]/div</value>
      <webElementGuid>78d11c31-2d51-46a1-a5a0-1738240df826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select State'])[1]/following::div[7]</value>
      <webElementGuid>e6998fb6-0bd8-4acf-b41e-71f1c3fa3409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and City'])[1]/following::div[12]</value>
      <webElementGuid>9cc57e0b-fc3b-4420-be02-34cc33806fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>0837b10b-03b3-4ac9-a0c7-6877cd876e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NCRUttar PradeshHaryanaRajasthan' or . = 'NCRUttar PradeshHaryanaRajasthan')]</value>
      <webElementGuid>6474503b-7d4d-4837-9932-fbb3c6ec9b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
